# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format test
version: "{build}"

shallow_clone: true

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

# What combinations to test
environment:
  nodejs_version: "5.5.0"

install:
  - ps: Install-Product node $env:nodejs_version x64
  # installing selenium-standalone
  - npm install -g selenium-standalone
  - selenium-standalone install
  # opening firewall ports
  - netsh advfirewall firewall add rule name="SeleniumIn" dir=in action=allow protocol=TCP localport=4444
  - netsh advfirewall firewall add rule name="SeleniumOut" dir=out action=allow protocol=TCP localport=4444
  # running selenium-standalone as background job
  - ps: Start-Process selenium-standalone start
  # installing local npm packages
  - npm install

build: off

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  # We test multiple Windows shells because of prior stdout buffering issues
  # filed against Grunt. https://github.com/joyent/node/issues/3584
  # - ps: "npm test # PowerShell" # Pass comment to PS for easier debugging
  # run local webdriverio
  - ./node_modules/.bin/wdio wdio.conf.js

# scripts to run after tests
on_finish :
#  - cmd: node afterTest.js
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json                                        # local npm modules
